### ISSUE TITLE
Missing Tables

### ISSUE THREAD

**Issue by beckindesigns** [divix1988/zf3dg_chapters#2]
Sorry if I am missing it but this book seems to jump all over the place. Where is the sql for creating the user_hobbies and the zend.comics table? Also, do you have a db dump file that I can use to create all the necessary rows and tables?

```
Zend\Db\Adapter\Exception\InvalidQueryException thrown with message "Statement could not be executed (42S02 - 1146 - Table 'zend.user_hobbies' doesn't exist)"

Table 'zend.comics' doesn't exist
```
Also appear to have an issue with the captcha?

`imageftbbox(): Could not read font`

**Comment by divix1988** [comment]
Page number 176, chapter 11.1 New controller:

```
CREATE TABLE IF NOT EXISTS `comics` (
	`id` int(10) unsigned AUTO_INCREMENT PRIMARY KEY NOT NULL,
	`title` varchar(200) NOT NULL,
	`thumb` varchar(100) NOT NULL
)

INSERT INTO `comics` (`id`, `title`, `thumb`) VALUES
	(1, 'batman', 'bat.png'),
	(2, 'spiderman', 'spider.jpg'),
	(3, 'thor', 'bolt.jpg'),
	(4, 'hulk', 'green.png'),
	(5, 'captain america', 'captain.jpg');
```

However you've seemed to renamed the table so change the above to your name.

`imageftbbox(): Could not read font`
Have you copied the TTF file to your folder correctly?
```
'font' => APPLICATION_PATH.'/public/fonts/arbli.ttf',
```
You can use any TTF font which you have on your machine it really doesn't matter.

**Comment by beckindesigns** [comment]
Thank you! What about the user_hobbies table sql code? Do you have a db dump available, it would be very helpful.

**Comment by divix1988** [comment]
`user_hobbies` table is listed on page numer: 167, Chapter 10.5.

```CREATE TABLE IF NOT EXISTS `user_hobbies` (
	`id` int(10) unsigned NOT NULL,
	`user_id` int(11) NOT NULL,
	`hobby` varchar(50) NOT NULL
)
```

Echo out the `APPLICATION_PATH.'/public/fonts/arbli.ttf'` and make sure the path is still correct with your font.
