### ISSUE TITLE
Wrong path on page 46 in the book

### ISSUE THREAD

**Issue by m-art-in** [divix1988/zf3dg_chapters#3]
On Page 46:

> Next we weill begin with the modification of the configuration... [...] To _config/global.php_ we will add...

Must be the path _config/autoload/global.php_, or?
same error twice on the page

**Comment by divix1988** [comment]
You are correct files: _local.php_ and _global.php_ are all located in _config/autoload/_ folder.

**Comment by m-art-in** [comment]
thank you for the confirmation
